### ISSUE TITLE
Как менять цвет иконок в svg-спрайте? 

### ISSUE THREAD

**Issue by MaxVilson** [nicothin/NTH-start-project#92]

**Comment by nicothin** [comment]
Для одноцветных иконок:

```css
.selector-of-svg-tag {
  fill: #bada55;
}
```
